import * as XLSX from 'xlsx';

export const downloadSampleExcel = () => {
  const sampleData = [
    {
      'Title': 'Mr',
      'First Name': 'John',
      'Last Name': 'Doe',
      'Preferred Name': 'Johnny',
      'Gender Identity': 'Male',
      'Preferred Pronouns': 'He/Him',
      'Date of Birth': '1955-08-15',
      'Marital Status': 'Married',
      'NHIS Number': 'NHS12345678',
      'Email': 'john.doe@example.com',
      'Phone': '+44 7123 456789',
      'Alternate Phone': '+44 7987 654321',
      'Login Email': 'johnny',
      'Password': 'SecurePass123!',
      'Primary Contact': 'Jane Doe',
      'Primary Contact Phone': '+44 7123 456780',
      'Primary Contact Email': 'jane.doe@example.com',
      'Secondary Contact': 'Robert Smith',
      'Secondary Contact Phone': '+44 7123 456781',
      'Secondary Contact Email': 'robert.smith@example.com',
      'Communication Preferences': 'Email and Phone',
      'Address Line': '123 Oak Street',
      'Town/City': 'Manchester',
      'County': 'Greater Manchester',
      'Postcode': 'M1 1AA',
      'Type of Residence': 'private_home',
      'Lives Alone': 'No',
      'Cohabitants': 'Wife and daughter',
      'Key Safe/Access Instructions': 'Key safe located under flower pot, code: 1234',
      'Next of Kin Name': 'Jane Doe',
      'Next of Kin Relationship': 'Wife',
      'Next of Kin Email': 'jane.doe@example.com',
      'Next of Kin Town': 'Manchester',
      'Next of Kin Phone 1': '+44 7123 456780',
      'Next of Kin Phone 2': '+44 7987 654320',
      'Preferred Care Times': '{"monday": {"available": true, "start": "07:00", "end": "19:00"}, "tuesday": {"available": true, "start": "07:00", "end": "19:00"}, "wednesday": {"available": true, "start": "07:00", "end": "19:00"}, "thursday": {"available": true, "start": "07:00", "end": "19:00"}, "friday": {"available": true, "start": "07:00", "end": "15:00"}, "saturday": {"available": true, "start": "09:00", "end": "13:00"}, "sunday": {"available": false}}'
    },
    {
      'Title': 'Mrs',
      'First Name': 'Mary',
      'Last Name': 'Smith',
      'Preferred Name': 'Mary',
      'Gender Identity': 'Female',
      'Preferred Pronouns': 'She/Her',
      'Date of Birth': '1948-03-22',
      'Marital Status': 'Widowed',
      'NHIS Number': 'NHS87654321',
      'Email': 'mary.alicejohnson@example.com',
      'Phone': '+44 7123 456790',
      'Alternate Phone': '+44 7987 654322',
      'Login Email': 'marysmith',
      'Password': 'MarySecure456!',
      'Primary Contact': 'David Smith',
      'Primary Contact Phone': '+44 7123 456791',
      'Primary Contact Email': 'david.smith@example.com',
      'Secondary Contact': 'Sarah Johnson',
      'Secondary Contact Phone': '+44 7123 456792',
      'Secondary Contact Email': 'sarah.johnson@example.com',
      'Communication Preferences': 'Phone only',
      'Address Line': '456 Pine Avenue',
      'Town/City': 'London',
      'County': 'Greater London',
      'Postcode': 'SW1A 1AA',
      'Type of Residence': 'assisted_living',
      'Lives Alone': 'Yes',
      'Cohabitants': '',
      'Key Safe/Access Instructions': 'Key with concierge, flat number 205',
      'Next of Kin Name': 'David Smith',
      'Next of Kin Relationship': 'Son',
      'Next of Kin Email': 'david.smith@example.com',
      'Next of Kin Town': 'London',
      'Next of Kin Phone 1': '+44 7123 456791',
      'Next of Kin Phone 2': '+44 7987 654323',
      'Preferred Care Times': '{"monday": {"available": false}, "tuesday": {"available": true, "start": "10:00", "end": "16:00"}, "wednesday": {"available": true, "start": "10:00", "end": "16:00"}, "thursday": {"available": true, "start": "10:00", "end": "16:00"}, "friday": {"available": false}, "saturday": {"available": false}, "sunday": {"available": false}}'
    },
    {
      'Title': 'Miss',
      'First Name': 'Alice',
      'Last Name': 'Johnson',
      'Preferred Name': 'Ali',
      'Gender Identity': 'Non-Binary',
      'Preferred Pronouns': 'They/Them',
      'Date of Birth': '1992-12-20',
      'Marital Status': 'Single',
      'NHIS Number': 'NHS56789012',
      'Email': 'alice.sirleaf@example.com',
      'Phone': '+44 7123 456793',
      'Alternate Phone': '+44 7987 654324',
      'Login Email': 'alicejohnson',
      'Password': 'AliceSecure789!',
      'Primary Contact': 'Charlie Johnson',
      'Primary Contact Phone': '+44 7123 456794',
      'Primary Contact Email': 'charlie.johnson@example.com',
      'Secondary Contact': 'Dana Wilson',
      'Secondary Contact Phone': '+44 7123 456795',
      'Secondary Contact Email': 'dana.wilson@example.com',
      'Communication Preferences': 'Email only',
      'Address Line': '789 Birch Lane',
      'Town/City': 'Birmingham',
      'County': 'West Midlands',
      'Postcode': 'B1 1TT',
      'Type of Residence': 'care_home',
      'Lives Alone': 'No',
      'Cohabitants': 'Care staff on duty',
      'Key Safe/Access Instructions': 'Smart lock - code sent via SMS',
      'Next of Kin Name': 'Charlie Johnson',
      'Next of Kin Relationship': 'Sibling',
      'Next of Kin Email': 'charlie.johnson@example.com',
      'Next of Kin Town': 'Birmingham',
      'Next of Kin Phone 1': '+44 7123 456794',
      'Next of Kin Phone 2': '+44 7987 654325',
      'Preferred Care Times': '{"monday": {"available": true, "start": "08:00", "end": "18:00"}, "tuesday": {"available": true, "start": "08:00", "end": "18:00"}, "wednesday": {"available": true, "start": "08:00", "end": "18:00"}, "thursday": {"available": true, "start": "08:00", "end": "18:00"}, "friday": {"available": true, "start": "08:00", "end": "18:00"}, "saturday": {"available": false}, "sunday": {"available": false}}'
    },
    {
      'Title': 'Dr',
      'First Name': 'Robert',
      'Last Name': 'Brown',
      'Preferred Name': 'Rob',
      'Gender Identity': 'Male',
      'Preferred Pronouns': 'He/Him',
      'Date of Birth': '1965-11-05',
      'Marital Status': 'Divorced',
      'NHIS Number': 'NHS34567890',
      'Email': 'robert.brown@example.com',
      'Phone': '+44 7123 456796',
      'Alternate Phone': '+44 7987 654326',
      'Login Email': 'robertbrown',
      'Password': 'RobertSecure101!',
      'Primary Contact': 'Lisa Brown',
      'Primary Contact Phone': '+44 7123 456797',
      'Primary Contact Email': 'lisa.brown@example.com',
      'Secondary Contact': 'Michael Wilson',
      'Secondary Contact Phone': '+44 7123 456798',
      'Secondary Contact Email': 'michael.wilson@example.com',
      'Communication Preferences': 'SMS and Email',
      'Address Line': '321 Elm Street',
      'Town/City': 'Leeds',
      'County': 'West Yorkshire',
      'Postcode': 'LS1 1AA',
      'Type of Residence': 'private_home',
      'Lives Alone': 'Yes',
      'Cohabitants': '',
      'Key Safe/Access Instructions': 'Front door key under mat',
      'Next of Kin Name': 'Lisa Brown',
      'Next of Kin Relationship': 'Ex-wife',
      'Next of Kin Email': 'lisa.brown@example.com',
      'Next of Kin Town': 'Leeds',
      'Next of Kin Phone 1': '+44 7123 456797',
      'Next of Kin Phone 2': '+44 7987 654327',
      'Preferred Care Times': '{"monday": {"available": true, "start": "09:00", "end": "17:00"}, "tuesday": {"available": true, "start": "09:00", "end": "17:00"}, "wednesday": {"available": true, "start": "09:00", "end": "17:00"}, "thursday": {"available": true, "start": "09:00", "end": "17:00"}, "friday": {"available": true, "start": "09:00", "end": "17:00"}, "saturday": {"available": false}, "sunday": {"available": false}}'
    },
    {
      'Title': 'Dr',
      'First Name': 'Emma',
      'Last Name': 'Davis',
      'Preferred Name': 'Emma',
      'Gender Identity': 'Female',
      'Preferred Pronouns': 'She/Her',
      'Date of Birth': '1958-07-14',
      'Marital Status': 'Married',
      'NHIS Number': 'NHS45678901',
      'Email': 'emma.davis@example.com',
      'Phone': '+44 7123 456799',
      'Alternate Phone': '+44 7987 654328',
      'Login Email': 'emmadavis',
      'Password': 'EmmaSecure202!',
      'Primary Contact': 'James Davis',
      'Primary Contact Phone': '+44 7123 456800',
      'Primary Contact Email': 'james.davis@example.com',
      'Secondary Contact': 'Sophie Taylor',
      'Secondary Contact Phone': '+44 7123 456801',
      'Secondary Contact Email': 'sophie.taylor@example.com',
      'Communication Preferences': 'Email and Phone',
      'Address Line': '654 Maple Drive',
      'Town/City': 'Glasgow',
      'County': 'Glasgow City',
      'Postcode': 'G1 1AA',
      'Type of Residence': 'sheltered',
      'Lives Alone': 'Yes',
      'Cohabitants': '',
      'Key Safe/Access Instructions': 'Key held by warden',
      'Next of Kin Name': 'James Davis',
      'Next of Kin Relationship': 'Husband',
      'Next of Kin Email': 'james.davis@example.com',
      'Next of Kin Town': 'Glasgow',
      'Next of Kin Phone 1': '+44 7123 456800',
      'Next of Kin Phone 2': '+44 7987 654329',
      'Preferred Care Times': '{"monday": {"available": true, "start": "06:00", "end": "22:00"}, "tuesday": {"available": true, "start": "06:00", "end": "22:00"}, "wednesday": {"available": true, "start": "06:00", "end": "22:00"}, "thursday": {"available": true, "start": "06:00", "end": "22:00"}, "friday": {"available": true, "start": "06:00", "end": "22:00"}, "saturday": {"available": true, "start": "06:00", "end": "22:00"}, "sunday": {"available": true, "start": "06:00", "end": "22:00"}}'
    }
  ];

  const ws = XLSX.utils.json_to_sheet(sampleData);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Sample Clients');
  XLSX.writeFile(wb, 'sample_clients.xlsx');
};