// Export the array of job titles
const jobTitles = [
  'customer service representative',
  'quality assurance engineer',
  'human resources manager',
  'software development engineer',
  'full stack software developer',
  'front end web developer',
  'back end web developer',
  'business intelligence analyst',
  'data science manager',
  'network security engineer',
  'project management specialist',
  'digital marketing specialist',
  'financial planning analyst',
  'senior software engineer',
  'junior software engineer',
  'technical support specialist',
  'database administrator',
  'marketing communications manager',
  'product development manager',
  'account executive',
  'account manager',
  'business analyst',
  'data analyst',
  'data scientist',
  'devops engineer',
  'software engineer',
  'project manager',
  'product manager',
  'sales manager',
  'graphic designer',
  'ui designer',
  'ux designer',
  'financial analyst',
  'security analyst',
  'system administrator',
  'network engineer',
  'consultant',
  'designer',
  'analyst',
  'engineer',
  'developer',
  'manager',
  'teacher',
  'nurse',
  'doctor',
  'pilot',
  'chef',
  'artist',
  'lawyer',
  'accountant',
  'electrician',
  'plumber',
  'mechanic',
  'scientist',
  'translator',
  'writer',
  'editor',
  'actor',
  'musician',
  'architect',
  'biologist',
  'chemist',
  'physicist',
  'pharmacist',
  'psychologist',
  'social worker',
  'therapist',
  'veterinarian',
  'zoologist',
  'web developer',
  'software tester',
  'system analyst',
  'sales associate',
  'customer support',
  'receptionist',
  'dispatcher',
  'driver',
  'security guard',
  'janitor',
  'cleaner',
  'laborer',
  'farmer',
  'gardener',
  'pilot',
  'flight attendant',
  'bartender',
  'waiter',
  'waitress',
  'cashier',
  'bank teller',
  'insurance agent',
  'real estate agent',
  'journalist',
  'photographer',
  'editor',
  'professor',
  'lecturer',
  'researcher',
  'administrator',
  'executive assistant',
  'legal assistant',
  'paralegal',
  'policy analyst',
  'economist',
  'statistician',
  'mathematician',
  'software architect',
  'cloud engineer',
  'mobile app developer',
  'game developer',
  'content writer',
  'seo specialist',
  'copywriter',
  'public relations specialist',
  'event coordinator',
  'logistics manager',
  'supply chain analyst',
  'warehouse manager',
  'construction worker',
  'civil engineer',
  'mechanical engineer',
  'electrical engineer',
  'chemical engineer',
  'environmental engineer',
  'pilot',
  'air traffic controller',
  'firefighter',
  'paramedic',
  'police officer',
  'military officer',
  'translator',
  'interpreter',
  'librarian',
  'museum curator',
  'artist',
  'musician',
  'actor',
  'director',
  'producer',
  'editor',
  'photographer',
  'graphic artist',
  'fashion designer',
  'interior designer',
  'chef',
  'baker',
  'barista',
  'mechanic',
  'plumber',
  'electrician',
  'carpenter',
  'welder',
  'truck driver',
  'pilot',
  'coach',
  'trainer',
  'personal trainer',
  'athlete',
  'coach',
  'teacher',
  'professor',
  'school principal',
  'counselor',
  'therapist',
  'psychologist',
  'social worker',
  'nurse',
  'doctor',
  'surgeon',
  'pharmacist',
  'dentist',
  'veterinarian',
  'research scientist',
  'lab technician',
  'biologist',
  'chemist',
  'physicist',
  'meteorologist',
  'geologist',
  'economist',
  'statistician',
  'financial advisor',
  'investment banker',
  'accountant',
  'auditor',
  'tax consultant',
  'lawyer',
  'judge',
  'paralegal',
  'policy analyst',
  'human resources specialist',
  'recruiter',
  'office manager',
  'executive assistant',
  'secretary',
  'customer service manager',
  'sales representative',
  'sales associate',
  'marketing manager',
  'brand manager',
  'advertising manager',
  'public relations manager',
  'event planner',
  'logistics coordinator',
  'supply chain manager',
  'operations manager',
  'business development manager',
  'entrepreneur',
];

export default jobTitles;
